### ISSUE TITLE
Unable to add dataset

### ISSUE THREAD

**Issue by MathyV** [cancan101/graphql-db-api#153]
I managed to get the package installed in Superset however I'm having difficulties adding a dataset. I'm using an on-premise Gitlab as the source. As you can see, the "tables" are loaded properly:

![image](https://user-images.githubusercontent.com/6393603/199697062-4060ee85-941f-455e-a1ea-81f5ed6733b1.png)

However, trying to add it, I get:

![image](https://user-images.githubusercontent.com/6393603/199697128-814360e4-f07d-4536-a915-bd6e6b6ae4ee.png)

And looking in the logs:

```
superset_app            | 2022-11-03 10:19:16,628:ERROR:root:list index out of range
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 86, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 113, in wraps
superset_app            |     raise ex
superset_app            |   File "/app/superset/views/base_api.py", line 110, in wraps
superset_app            |     duration, response = time_function(f, self, *args, **kwargs)
superset_app            |   File "/app/superset/utils/core.py", line 1507, in time_function
superset_app            |     response = func(*args, **kwargs)
superset_app            |   File "/app/superset/utils/log.py", line 245, in wrapper
superset_app            |     value = f(*args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 83, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/datasets/api.py", line 267, in post
superset_app            |     new_model = CreateDatasetCommand(g.user, item).run()
superset_app            |   File "/app/superset/datasets/commands/create.py", line 46, in run
superset_app            |     self.validate()
superset_app            |   File "/app/superset/datasets/commands/create.py", line 86, in validate
superset_app            |     if database and not DatasetDAO.validate_table_exists(
superset_app            |   File "/app/superset/datasets/dao.py", line 83, in validate_table_exists
superset_app            |     database.get_table(table_name, schema=schema)
superset_app            |   File "/app/superset/models/core.py", line 678, in get_table
superset_app            |     return Table(
superset_app            |   File "<string>", line 2, in __new__
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
superset_app            |     return fn(*args, **kwargs)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 563, in __new__
superset_app            |     metadata._remove_table(name, schema)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
superset_app            |     compat.raise_(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
superset_app            |     raise exception
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 558, in __new__
superset_app            |     table._init(name, metadata, *args, **kw)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 647, in _init
superset_app            |     self._autoload(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 670, in _autoload
superset_app            |     autoload_with.run_callable(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2212, in run_callable
superset_app            |     return conn.run_callable(callable_, *args, **kwargs)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1653, in run_callable
superset_app            |     return callable_(self, *args, **kwargs)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 484, in reflecttable
superset_app            |     return insp.reflecttable(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 664, in reflecttable
superset_app            |     for col_d in self.get_columns(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 390, in get_columns
superset_app            |     col_defs = self.dialect.get_columns(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/shillelagh/backends/apsw/dialects/base.py", line 128, in get_columns
superset_app            |     adapter = get_adapter_for_table_name(connection, table_name)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/shillelagh/backends/apsw/dialects/base.py", line 159, in get_adapter_for_table_name
superset_app            |     return adapter(*args, **kwargs)  # type: ignore
superset_app            |   File "/usr/local/lib/python3.8/site-packages/graphqldb/adapter.py", line 254, in __init__
superset_app            |     edges_type_name = get_edges_type_name(query_return_fields)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/graphqldb/adapter.py", line 136, in get_edges_type_name
superset_app            |     edges_info = find_type_by_name("edges", types=fields)["ofType"]
superset_app            |   File "/usr/local/lib/python3.8/site-packages/graphqldb/adapter.py", line 132, in find_type_by_name
superset_app            |     return find_by_name(name, types=types)["type"]
superset_app            |   File "/usr/local/lib/python3.8/site-packages/graphqldb/adapter.py", line 128, in find_by_name
superset_app            |     return [x for x in types if x["name"] == name][0]
superset_app            | IndexError: list index out of range
```

Any pointers are appreciated...

**Comment by MathyV** [comment]
Looking at the code of the last functions in the stack trace it seems like you are presuming at least one result will always be found. I'm not that familiar with graphql but are you sure that is the case? 

I'll try to setup a dev environment myself to have a closer look but haven't succeeded in that so far, just running from docker images right now.

**Comment by cancan101** [comment]
Agreed it looks like I am making some assumption that is not holding for you.

Are you able to share the schema? At the very least the query you are trying to access and its return type?

**Comment by cancan101** [comment]
I also just published a new version, `0.0.1.dev2` to pypi. It probably won't fix your issue, but at least line numbers should more closely match what is in `main`.

**Comment by MathyV** [comment]
I'm trying to access the Gitlab API, it's documented here:
https://docs.gitlab.com/ee/api/graphql/reference/

For the `currentUser` table, this would be the query
```
query { currentUser {name} }
```
And this would be the result
```
{
  "data": {
    "currentUser": {
      "name": "Mathy"
    }
  }
}
```

**Comment by cancan101** [comment]
Ah ok. That would be a scalar though (object). Right we expect the top level to be an iterable (connection or list) and we actually just support connections: https://github.com/cancan101/graphql-db-api#roadmap

**Comment by MathyV** [comment]
Are you then talking about the data object?

This query
```
query { projects {nodes{name}}}
```
Results in multiple objects

```
{
  "data": {
    "projects": {
      "nodes": [
        {
          "name": "Project 1"
        },
        {
          "name": "Project 2"
        },
        {
          "name": "Project 3"
        }
      ]
    }
  }
}
```
But as you can see, they're still grouped under the "data" object. It would be good if for the dataset instead of (or in addition to) the name of the "table" we could just specify a path to the resultset that we desire. Like in this case `data.projects.nodes`, but I guess that's what you mean with Path Traversal in your roadmap.

**Comment by cancan101** [comment]
The issue is that we are assuming the top level is a `Connection` rather than a `List`.

We are already reading  values under `data`: https://github.com/cancan101/graphql-db-api/blob/115a8e5e94b56b9606aa60245cb8dccc8572363a/graphqldb/lib.py#L59 as that is part of the [graphql spec](https://spec.graphql.org/June2018/#sec-Data)

In addition we are reading the `query` name (the "table" in SQL), which in your case would be projects: https://github.com/cancan101/graphql-db-api/blob/115a8e5e94b56b9606aa60245cb8dccc8572363a/graphqldb/adapter.py#L413

We right now assume that there are edges and nodes:
https://github.com/cancan101/graphql-db-api/blob/115a8e5e94b56b9606aa60245cb8dccc8572363a/graphqldb/adapter.py#L415-L416

and likewise when we build the query itself:
https://github.com/cancan101/graphql-db-api/blob/115a8e5e94b56b9606aa60245cb8dccc8572363a/graphqldb/adapter.py#L402-L411

You actually are not hitting any of this code as the same assumptions exist in the [introspection where we do some type decoding](https://github.com/cancan101/graphql-db-api/blob/115a8e5e94b56b9606aa60245cb8dccc8572363a/graphqldb/adapter.py#L304-L344) assuming there is a Connection. All of this can be fixed (and in fact should be simpler logic than already exists for the Connection).

**Comment by cancan101** [comment]
Actually this should work for you as GitLab supports Connection:
https://docs.gitlab.com/ee/api/graphql/reference/#projectconnection
from: https://docs.gitlab.com/ee/api/graphql/reference/#queryprojects

is there a public API I can test this with?

**Comment by cancan101** [comment]
Looking back at your initial post, it seems you were request the `currentUser` (scalar) rather than something like `projects`:
![image](https://user-images.githubusercontent.com/51059/200027593-bb56eb38-81c7-4641-ab1f-e4b9fc87955d.png)

**Comment by cancan101** [comment]
Ok, I actually had a GitLab instance lying around. I was able to test all this and `projects` works fine with this fix: https://github.com/cancan101/graphql-db-api/pull/155 adding support for `Time` scalars.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/51059/200032363-735918c0-b2cf-4b12-a1cf-779a1828974b.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/51059/200033092-01f9e728-b61c-4d13-b404-55d21db4028e.png">


though as it turns out GitLab's `Time` scalar is actually a date: https://docs.gitlab.com/ee/api/graphql/reference/index.html#time
which is really odd: https://www.the-guild.dev/graphql/scalars/docs/scalars/time

**Comment by cancan101** [comment]
The `Time` fix has been merged and published to pypi. Otherwise everything else should work as is. LMK if you run into an issue.

**Comment by cancan101** [comment]
Closing this for now. re-open if you have issues

**Comment by MathyV** [comment]
Waw, what a great response time :-) My ultimate goal is to create a report on the user timesheets, will let you know with the information you provided if that works out.
