### ISSUE TITLE
Why do we need to depend on "edges" and "node" keywords

### ISSUE THREAD

**Issue by SatvikNema** [cancan101/graphql-db-api#223]
Say I have a simple schema without edges and nodes
```graphql
type Query {
    simpleQueryList(n: Int): [MyResponse]
}

type MyResponse {
    number: Int
    id: String
}

```

1. How can this package handle that scenario? A different parsing then would be required in adapter.py.
2. Why do we need to stick to keywords "edges" and "node"

**Comment by cancan101** [comment]
Totally reasonable questions!

These are know limitations of the current code outlined here: https://github.com/cancan101/graphql-db-api#roadmap, especially the "Non-Connections top level". Adapting the code to support lists on top level should be relatively easy. 

Would involve some changes here: https://github.com/cancan101/graphql-db-api/blob/b87978e6f664cd6cdd0ee0c2fc0bbf5de5b7f664/graphqldb/adapter.py#L325-L340
and then:
https://github.com/cancan101/graphql-db-api/blob/b87978e6f664cd6cdd0ee0c2fc0bbf5de5b7f664/graphqldb/adapter.py#L419-L420

Code changes are probably pretty simple, it's mostly a matter of choosing how the user specifies this vs if it is introspected (which could be done, at least for a v1).

As far as where the names "edges" and "node" come from, that is the [GraphQL Cursor Connections Specification](https://relay.dev/graphql/connections.htm). Presumably those string names could be passed in if we wanted to support Connections that used different keywords, though to be honest I have not seen that in the wild.

**Comment by SatvikNema** [comment]
Asking because I have seen many schemas which dont use the concept of node and edges. Most of the use cases might be with simple non connections. 
Any plans of adding that in near future?

I am pretty new to python and was checking out dashboard capabilities of superset, and stumbled upon this awesome adapter. It's a nice package!

**Comment by cancan101** [comment]
This PR adds the functionality: https://github.com/cancan101/graphql-db-api/pull/234

I can't promise as is that it is robust to all forms of GQL types. I am making certain assumption as to nullness, etc.

I am not in live with the API either (you to pass in `is_connection=0`.

**Comment by SatvikNema** [comment]
Thanks @cancan101 for working on this.
Will check your changes

**Comment by cancan101** [comment]
Closing this for the time being as basic non-connection support has been added.
