### ISSUE TITLE
Connect to arbitrary GraphQL 

### ISSUE THREAD

**Issue by gtsiatsios** [cancan101/graphql-db-api#321]
According to this project I want to connect an arbitrary GraphQL API with Superset with this component help.
Successfully I have installed the component and use Swapi: `graphql://swapi-graphql.netlify.app/.netlify/functions/index`
How should I connect another GraphQL API? should I have a specific path for the API? 
Are you able to connect your API via your component with superset? If so how ? Should I create something specific from GraphQL  site?

Thanks

**Comment by cancan101** [comment]
Is there a specific GraphQL that you are looking to connect to? You would then map the URL of that to a connection string. Here are some examples in the docs:
```
# Over HTTPS (default):
engine_https = create_engine('graphql://host:port/path')

# Over HTTP:
engine_http = create_engine('graphql://host:port/path?is_https=0')

# With a `Bearer` token in the `Authorization` header:
engine_http = create_engine('graphql://:token@host:port/path')
```

**Comment by gtsiatsios** [comment]
I have my own GraphQL API: http://something:8000 and I am interested to connect it with Superset via this your module. I have successfully installed the module in Superset, but can't access my API. 
Should I do anything specific to my API to be able the module to connect with it and therefore use it in Superset?

**Comment by gtsiatsios** [comment]
I have clone your code and start digging. The test works. When I add my link as you suggested it works also (for me ```graphql://something:8000/graphql? is_https=0``` ) I am able to view my API Calls as tables and query as in the test above. 
I use  graphql with strawberry and I use DataClasses to define tables. 
My aim is to view my API calls from Superset as tables , but adding the link doesn't work in Superset.

Should I do some integration to work in Superset?



![Screenshot 2023-07-19 at 23 19 22](https://github.com/cancan101/graphql-db-api/assets/113906172/74ad3800-a8e7-402b-8f32-159dcf88522c)


Selecting any of the above I get from Superset:

```
superset_app                  | Traceback (most recent call last):
superset_app                  |   File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
superset_app                  |     return f(self, *args, **kwargs)
superset_app                  |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app                  |     raise ex
superset_app                  |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app                  |     duration, response = time_function(f, self, *args, **kwargs)
superset_app                  |   File "/app/superset/utils/core.py", line 1523, in time_function
superset_app                  |     response = func(*args, **kwargs)
superset_app                  |   File "/app/superset/utils/log.py", line 255, in wrapper
superset_app                  |     value = f(*args, **kwargs)
superset_app                  |   File "/app/superset/databases/api.py", line 728, in table_metadata
superset_app                  |     table_info = get_table_metadata(database, table_name, schema_name)
superset_app                  |   File "/app/superset/databases/utils.py", line 67, in get_table_metadata
superset_app                  |     columns = database.get_columns(table_name, schema_name)
superset_app                  |   File "/app/superset/models/core.py", line 843, in get_columns
superset_app                  |     return self.db_engine_spec.get_columns(inspector, table_name, schema)
superset_app                  |   File "/app/superset/db_engine_specs/base.py", line 1244, in get_columns
superset_app                  |     cast(list[SQLAColumnType], inspector.get_columns(table_name, schema))
superset_app                  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
superset_app                  |     col_defs = self.dialect.get_columns(
superset_app                  |   File "/usr/local/lib/python3.9/site-packages/shillelagh/backends/apsw/dialects/base.py", line 129, in get_columns
superset_app                  |     adapter = get_adapter_for_table_name(connection, table_name)
superset_app                  |   File "/usr/local/lib/python3.9/site-packages/shillelagh/backends/apsw/dialects/base.py", line 160, in get_adapter_for_table_name
superset_app                  |     return adapter(*args, **kwargs)  # type: ignore
superset_app                  |   File "/usr/local/lib/python3.9/site-packages/graphqldb/adapter.py", line 380, in __init__
superset_app                  |     raise ValueError(
superset_app                  | ValueError: Unable to resolve query_return_type_name for Orders
```

**Comment by cancan101** [comment]
Is `Orders` a `Connection` or just a `List?` If a list, you will need to set the table name to (quotes are important): `'Orders?is_connection=0'`.

**Comment by gtsiatsios** [comment]
![Screenshot 2023-07-20 at 10 26 47](https://github.com/cancan101/graphql-db-api/assets/113906172/fb4d9fc1-f39a-4520-b508-725e8dddf740)

With the query I am able to view my data successfully, but I want to be able to view the columns also on the left side

**Comment by cancan101** [comment]
So some quick testing:
- I am having better luck on Superset `1.5.1` rather than `master`. I do have test more to understand limitations / issues of `master`. There may be some new methods that need to be exposed on the gql dialect to get table / column introspection working
- `is_connection=0` does _not_ seem to work for Superset as far as creating a dataset. There is an issue in that I cannot even add the dataset to _then_ set the `is_connection=0` flag if there is not a top level connection. This is a "bug" on the gql dialect side. One way to fix this would be to not error in the case of non connection and another would be to allow specifying `is_connection=0` at the database level (ie in the connection string) rather than at the table level.

In the case of the SWAP api (top level connection) (`graphql://swapi-graphql.netlify.app/.netlify/functions/index`), you do get some nice introspection of columns:
![image](https://github.com/cancan101/graphql-db-api/assets/51059/c195fce7-9f78-4fbb-b457-cf6be0af65eb)
![image](https://github.com/cancan101/graphql-db-api/assets/51059/90162ea2-02ac-46e1-8b33-82c78bfc2a2e)

I was able to add the query params using the Legacy Editor _after_ I first created the dataset. Unfortunately that does not work at present with the non connection:
![image](https://github.com/cancan101/graphql-db-api/assets/51059/bf0acb9b-3fe9-469c-8311-94e51169e0be)

**Comment by gtsiatsios** [comment]
Perfect. Thank you for checking. Would you be able to push in order to test it ? Would this work even you have to pass arguments in the query ? 
eg. graphql api has some mandatory filters/arguments or this stands? 

``` I was able to add the query params using the Legacy Editor after I first created the dataset. Unfortunately that does not work at present with the non connection: ```

**Comment by cancan101** [comment]
>Would you be able to push in order to test it

Technically it is already pushed to a branch on GH. You can actually pip install from a git branch. I don't remember the syntax off the top of my head.

>Would this work even you have to pass arguments in the query ?

Probably. Can you can give me a can example of what you mean?

**Comment by cancan101** [comment]
This was merged to `main`. I ended up calling the parameter: `list_queries`.

**Comment by cancan101** [comment]
I believe this works on superset's master. Just make sure that if you are working with a local build, you rebuild front end assets ;-)

**Comment by gtsiatsios** [comment]
First of all sorry for my late answer.
It works as expected thank you.

I want to do something like this:

```
def test_query_non_connection(connection: Connection) -> None:
    """Test querying against a non-connection (i.e. a List)."""
    result = connection.execute(
        text(
            """select
                name
            from
                'table?is_connection=0&iarg_to="""'2021-02-01'"""&iarg_from="""'2021-01-01'"""'"""
        )
    )

```
By adding some code I achieved that. Basically I want the query to accept some arguments.

**Comment by gtsiatsios** [comment]
ok thank you!
