### ISSUE TITLE
Package releases

### ISSUE THREAD

**Issue by rhyder** [cancan101/graphql-db-api#335]
Hi thanks for this library!

I am installing it via https://pypi.org/project/sqlalchemy-graphqlapi/#history - how often will you release? I am keen to try out the changes recently merged via https://github.com/cancan101/graphql-db-api/commit/fd18c0de4d9b41c3849956bd861907981ef8dcbf

thanks

**Comment by cancan101** [comment]
I just published an update to pypi.
