### ISSUE TITLE
Is this project further developed?

### ISSUE THREAD

**Issue by rutemja** [cancan101/graphql-db-api#355]
Hi, 
we are currently looking for a "Dashboard-Tool" that can consume GraphQL and this looks awesome. 
Is someone using this in production (version 'v0.0.1.dev5' does not look like)?
Are you still investing time in this project, especially in the advanced auth feature?

**Comment by cancan101** [comment]
I am not actively developing the project, though I am happy to respond to tickets and help guide anyone that wants to PR new functionality.
